# Introduction {#intro}

The Nordic countries are world-famous for their social protection model. The model is known under several names: the Scandinavian, Nordic, Social Democratic, institutional, universal, egalitarian, encompassing, or social investment model. Each name refers to different aspects of the model. Scandinavian and Nordic refer to the geographical entity, a geographically exclusive definition that rules out all other countries from the model. The Nordic welfare state can be found only in the North. Since the name pertains to geography, it does not matter what happens in the level of benefits or in the institutional construction for delivering benefits. The model will continue to be Nordic. 

Some basic historical developmental patterns can be discerned. Poor laws and modest social services were the first forms of official social policy in the Nordic countries. Municipalities became gradually responsible for expanding welfare obligations and even now, social services are delivered by local authorities that have their own political sovereignty and rights to collect taxes to finance services they provide. Within certain limits, the municipalities can decide on their own welfare activities and municipal tax rates to finance those activities (Kangas & Palme, 2005). This combination of centralized state and local democratic decision-making had important ramification for the subsequent development of the Nordic societies. The distance between the state/public sector and civil society became close and blurred, and often it is hard to say where civil society ends and the public sector begins. In the Nordic countries, “state” is often used synonymously with “society” (Allardt, 1986; Alestalo & Kuhnle, 1987).

The Nordic countries differ in the timing of their first social policy programs. Usually Denmark and Sweden led and Norway and Finland followed a decade or so later. For example, Denmark was one of the first countries in the world to implement a pension law (1891), followed by Iceland (1909) and Sweden (1913), whereas Norway (1936) and Finland (1937) were late adopters. In work-accident insurance the order was reversed: Norway introduced the first scheme in 1894, followed by Finland a year later, while Denmark and Sweden implemented such laws in 1916, and Iceland in 1925. Whereas Sweden was first to complement statutory earnings-related pensions (in 1959), Finland was second (1962), and Norway third (1966); Denmark and Iceland never managed to legislate income-related pensions, but the need for income-loss compensations bifurcated into private individual and labor-market pensions (Kangas, Lundberg, & Ploug, 2010. In child benefits, Iceland and Norway led (1946), closely followed by Sweden (1947), Finland (1948), and Denmark (1952). In family policy and other social services, Sweden generally led. However, if one inspects the development in these countries diachronically, many similarities exist. The countries follow a similar path but the chronology is different. Today, they are all modern, comprehensive welfare states and changes in their social policies take place more or less simultaneously. However, the Nordic countries are not identical and it is said that the Nordic model is a model with five exceptions (Christiansen & al. 2006). 

In this chapter we focus on the principles, policies, and outcomes in the Nordic welfare state. In the next section we discuss how social democratic the Nordic welfare state still is. Thereafter we briefly describe legislated social rights in terms of universality and generosity. Extensive rights demand extensive spending, and to finance such extensive spending, tax rates must be relatively high. Indeed, heavy spending and a heavy tax burden have often been regarded as emblems of a well-developed welfare state and hence of the model. One of the main – albeit not the only – tasks of the welfare state is to combat poverty. Another important task is to invest in people to provide them with capacities to cope if various social risks materialize. This social investment aspect is very important for children. These issues, that is, protection and investment, are scrutinized in the third section. The penultimate section concentrates on female labor-force participation, and in the final section we summarize our findings on the Nordic welfare-state model and whether it still is warranted to speak of it.
