# Conclusions

The Nordic welfare state has been labeled in many different ways and epithets are many. Regarding the geographical dimension of the model, one can argue that the Nordic model will always be Nordic if the model pertains to the five countries on the northern edge of Europe. However, institutional characteristics may vary from country to country.

Many analysts have paid attention to cultural heritage similarities and to political forces that are regarded as responsible for designing the welfare-state models we find in different parts of the world. In this context, it is customary to speak about the social democratic model. To some extent this is warranted. However, the historical power positions of the Nordic Social Democratic parties vary: in Sweden they clearly had an upper hand and perhaps the same goes for Norway and Denmark. In contrast to the three Scandinavian kingdoms, the two republics, Finland and Iceland, display different patterns. In Finland, establishing social policy programs was more consensual and characterized by numerous political compromises between the social democrats and other parties. In Iceland, Social Democracy has not gathered such popular support as in the other four Nordic countries. Thus, there are substantial differences in the nature of “Social Democracy,” in particular between Sweden and Iceland. With the exception of Iceland, political support for Social Democracy has been declining. Due to these trends, the Nordic countries have become more similar, but simultaneously they have become less “Social Democratic” and perhaps it is time to stop speaking of the Social Democratic model and instead to look at social policy institutions and their consequences and various outcomes.

Our study indicates that welfare-state regimes – including the Nordic one – may converge and lose their distinctiveness in two ways. First, the countries in a regime may abandon the central aspect of the ideal model. The Nordic countries might introduce more means testing and income testing in their transfer programs, increase conditionality, and implement higher user fees for previously free social services. Thus, the model is losing the praised universality and free services, and beginning to resemble other welfare models. Second, even though the countries in the Nordic regime may faithfully maintain and even fortify the central characteristics of their model, other countries adapting the same characteristics may “go Nordic” and catch up, and consequently, the differences will erode.

We looked at four dimensions that are fundamental for the Nordic welfare-state regime – clearly, each of them deserved to be analyzed on its own: 1) high level of social rights, 2) high level of social spending and taxation, 3) the consequent low incidence of poverty, and 4) the “woman-friendliness” of the welfare state. These were measured in terms of possibilities to participate in labor-market activities and in terms of the low level of work absences due to various family obligations.

For the first dimension, we found signs of both types of convergence and a dilution of clear regime contours. While the Nordic countries are maintaining their high level of coverage in social protection, some of them have cut benefit levels. Simultaneously, some non-Nordic countries have increased their performance in terms of coverage and generosity and are catching up to the Nordics. Nevertheless, the Nordic nations still form a group characterized by high benefits and high coverage among the populace, but many other countries have entered the same group.

Regarding the levels and items of spending, collecting revenues via taxes, and social security contributions, we find country-specific variations. Currently Denmark, Finland, and Sweden are big spenders with relatively high tax rates. Except Finland, the other Nordic countries are social-service states in contrast to the Central European transfer states. Whereas Denmark relies on taxes and does not much use social security contributions, employer and employee fees play an important role in Finland and Sweden. Norway and Iceland fall in between.

Perhaps the strongest degree of sameness between the five Nordics can be seen in outcomes. All five countries display low levels of income poverty and material deprivation. In particular, in comparison to other countries, the incidence of poverty among children is low, and in that respect the Nordic countries are in a unique group. In addition, intra-generational mobility is high, an indication that the Nordic societies are rather open and that family background does not play so important a role as in many other rich nations.

What about the woman friendliness of the Nordic model? In the Nordics, female employment levels are the highest in the OECD hemisphere, but even here we find convergences of the second type: other countries are going Nordic and catching up, and gradually their female employment patterns are approaching Nordic ones. One important aspect is the kind of consequences that care-related institutions have upon female employment rates and care-related absences from the labor market. Our analyses based on the EU-SILC data showed that with the exception of Finland, in Scandinavia care-related absences from the labor markets are short and evenly distributed over the working-life cycle.

All in all, our results indicate that despite some signs of a piecemeal convergence among wealthy nations, a high degree of welfare-state “regime integrity” remains. It still is possible to talk about a specific welfare model followed by the five Nordic countries. The Nordic welfare model today is less universal, less generous, and more conditional than it was 20 years ago. However, the Nordic welfare model is still distinct and fares well in comparison with other welfare-state models on most dimensions of welfare. Poverty and inequality rates are low, income mobility – be it short-term or inter-generational – is high, as is the level of subjective welfare. All this is very much in line with the basic Nordic ideas about how the state should work: it should provide individuals with resources to master their own lives. Whether the Nordic welfare model can continue to do so seems to be as much a question of political decisions as of harsh economic or social realities.
